export default {
  "login": "enixam",
  "id": 48123899,
  "node_id": "MDQ6VXNlcjQ4MTIzODk5",
  "avatar_url": "https://avatars.githubusercontent.com/u/48123899?v=4",
  "gravatar_id": "",
  "url": "https://api.github.com/users/enixam",
  "html_url": "https://github.com/enixam",
  "followers_url": "https://api.github.com/users/enixam/followers",
  "following_url": "https://api.github.com/users/enixam/following{/other_user}",
  "gists_url": "https://api.github.com/users/enixam/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/enixam/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/enixam/subscriptions",
  "organizations_url": "https://api.github.com/users/enixam/orgs",
  "repos_url": "https://api.github.com/users/enixam/repos",
  "events_url": "https://api.github.com/users/enixam/events{/privacy}",
  "received_events_url": "https://api.github.com/users/enixam/received_events",
  "type": "User",
  "site_admin": false,
  "name": "Qiushi",
  "company": "Communication University of China",
  "blog": "https://qiushi.rbind.io/",
  "location": "Beijing",
  "email": null,
  "hireable": null,
  "bio": null,
  "twitter_username": "qiushizzzz",
  "public_repos": 76,
  "public_gists": 1,
  "followers": 35,
  "following": 533,
  "created_at": "2019-03-01T11:09:55Z",
  "updated_at": "2021-02-13T11:09:24Z"
}