export default {
  "login": "qiushiyan",
  "id": 48123899,
  "node_id": "MDQ6VXNlcjQ4MTIzODk5",
  "avatar_url": "https://avatars.githubusercontent.com/u/48123899?v=4",
  "gravatar_id": "",
  "url": "https://api.github.com/users/qiushiyan",
  "html_url": "https://github.com/qiushiyan",
  "followers_url": "https://api.github.com/users/qiushiyan/followers",
  "following_url": "https://api.github.com/users/qiushiyan/following{/other_user}",
  "gists_url": "https://api.github.com/users/qiushiyan/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/qiushiyan/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/qiushiyan/subscriptions",
  "organizations_url": "https://api.github.com/users/qiushiyan/orgs",
  "repos_url": "https://api.github.com/users/qiushiyan/repos",
  "events_url": "https://api.github.com/users/qiushiyan/events{/privacy}",
  "received_events_url": "https://api.github.com/users/qiushiyan/received_events",
  "type": "User",
  "site_admin": false,
  "name": "Qiushi Yan",
  "company": "Vanderbilt University",
  "blog": "qiushiyan.dev",
  "location": null,
  "email": null,
  "hireable": null,
  "bio": null,
  "twitter_username": null,
  "public_repos": 54,
  "public_gists": 1,
  "followers": 45,
  "following": 560,
  "created_at": "2019-03-01T11:09:55Z",
  "updated_at": "2021-10-05T15:26:51Z"
}